import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class', '[data-theme="dark"]'],
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Livewire/**/*.php',
        './app/Domains/**/*.php',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['"Reddit Sans"', 'system-ui', 'sans-serif'],
                body: ['"Reddit Sans"', 'system-ui', 'sans-serif'],
                display: ['"Reddit Sans"', 'system-ui', 'sans-serif'],
                mono: ['"Reddit Sans"', 'system-ui', 'sans-serif'],
            },
            colors: {
                primary: {
                    100: 'var(--colors-primary-g100)',
                    500: 'var(--colors-primary-g500)',
                    600: 'var(--colors-primary-g600)',
                },
                mono: {
                    white: 'var(--colors-mono-white)',
                    black: 'var(--colors-mono-black)',
                    50: 'var(--colors-mono-g50)',
                    100: 'var(--colors-mono-g100)',
                    200: 'var(--colors-mono-g200)',
                    300: 'var(--colors-mono-g300)',
                    400: 'var(--colors-mono-g400)',
                    600: 'var(--colors-mono-g600)',
                    900: 'var(--colors-mono-g900)',
                },
                up: 'var(--colors-up)',
                'up-bg': 'var(--colors-up-bg)',
                down: 'var(--colors-down)',
                'down-bg': 'var(--colors-down-bg)',
                error: 'var(--colors-error)',
                success: 'var(--colors-success)',
                'success-bg': 'var(--colors-success-bg)',
                info: 'var(--colors-info)',
                'info-bg': 'var(--colors-info-bg)',

                /* Compatibilidade temporaria com as telas ainda nao migradas. */
                cryptex: {
                    bg: {
                        primary: 'var(--bg-primary)',
                        secondary: 'var(--bg-secondary)',
                        tertiary: 'var(--bg-tertiary)',
                        elevated: 'var(--bg-elevated)',
                        overlay: 'var(--bg-overlay)',
                    },
                    text: {
                        primary: 'var(--text-primary)',
                        secondary: 'var(--text-secondary)',
                        tertiary: 'var(--text-tertiary)',
                        disabled: 'var(--text-disabled)',
                        inverse: 'var(--text-inverse)',
                    },
                    brand: {
                        50: 'var(--brand-50)',
                        100: 'var(--brand-100)',
                        200: 'var(--brand-200)',
                        300: 'var(--brand-300)',
                        400: 'var(--brand-400)',
                        500: 'var(--brand-500)',
                        600: 'var(--brand-600)',
                        700: 'var(--brand-700)',
                    },
                    green: {
                        400: 'var(--green-400)',
                        500: 'var(--green-500)',
                        600: 'var(--green-600)',
                    },
                    red: {
                        400: 'var(--red-400)',
                        500: 'var(--red-500)',
                        600: 'var(--red-600)',
                    },
                    blue: {
                        400: 'var(--blue-400)',
                    },
                    orange: {
                        400: 'var(--orange-400)',
                    },
                    purple: {
                        400: 'var(--purple-400)',
                    },
                    border: {
                        subtle: 'var(--border-subtle)',
                        default: 'var(--border-default)',
                        strong: 'var(--border-strong)',
                    },
                },
            },
            spacing: {
                xxxs: '0.25rem',
                xxs: '0.5rem',
                xs: '0.75rem',
                sm: '1rem',
                md: '1.25rem',
                lg: '1.5rem',
                xl: '2rem',
                xxl: '2.5rem',
                'space-1': '4px',
                'space-2': '8px',
                'space-3': '12px',
                'space-4': '16px',
                'space-5': '20px',
                'space-6': '24px',
                'space-8': '32px',
                'space-10': '40px',
                'space-12': '48px',
                'space-16': '64px',
                'space-20': '80px',
            },
            borderRadius: {
                xs: '4px',
                sm: '8px',
                md: '12px',
                lg: '16px',
                xl: '20px',
                '2xl': '16px',
                '3xl': '20px',
                pill: '999px',
            },
            boxShadow: {
                card: 'var(--shadow-card)',
                dropdown: 'var(--shadow-dropdown)',
                elevated: 'var(--shadow-elevated)',
                glow: 'var(--shadow-glow)',
            },
            fontSize: {
                xxs: ['0.625rem', { lineHeight: '1.2' }],
                'fs-12': '0.75rem',
                'fs-14': '0.875rem',
                'fs-16': '1rem',
                'fs-18': '1.125rem',
                'fs-20': '1.25rem',
                'fs-24': '1.5rem',
                'fs-32': '2rem',
                'fs-40': '2.5rem',
                'fs-56': '3.5rem',
            },
            zIndex: {
                dropdown: '100',
                modal: '1000',
            },
            transitionTimingFunction: {
                out: 'cubic-bezier(0.16, 1, 0.3, 1)',
                spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
            },
            transitionDuration: {
                fast: '150ms',
                base: '250ms',
                slow: '400ms',
            },
        },
    },
    plugins: [forms],
};
